modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "MIT"

issueTrackerURL = "https://github.com/TripleCheck/issues"

[[mods]]
modId = "triplecheck"
version = "${file.jarVersion}"
displayName = "Triple Check"
displayURL = "https://github.com/"
logoFile = "logo.png"
credits = ""
authors = "Talia"
description = "A library for unit testing Minecraft mods (Forge and Fabric)."

[[dependencies.triplecheck]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.triplecheck]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
